from envs import (
    TAURON_PASSWORD1, TAURON_USERNAME1, PESEL1, TAURON_USERNAME2, TAURON_PASSWORD2,
    PESEL2, PGG_PASSWORD1, PGG_USERNAME1, PGG_PASSWORD2, PGG_USERNAME2, TAURON_USERNAME3,
    TAURON_PASSWORD3, PESEL3
)





TAURON_ACCOUNT_1 = Account(TAURON_USERNAME1, TAURON_PASSWORD1, PESEL1)
TAURON_ACCOUNT_2 = Account(TAURON_USERNAME2, TAURON_PASSWORD2, PESEL2)
TAURON_ACCOUNT_3 = Account(TAURON_USERNAME3, TAURON_PASSWORD3, PESEL3)

PGG_ACCOUNT_1 = Account(PGG_USERNAME1, PGG_PASSWORD1, PESEL1)
PGG_ACCOUNT_2 = Account(PGG_USERNAME2, PGG_PASSWORD2, PESEL2)


ALL_TAURON_ACCOUNTS = [TAURON_ACCOUNT_1, TAURON_ACCOUNT_2, TAURON_ACCOUNT_3]
ALL_PGG_ACCOUNTS = [PGG_ACCOUNT_1]


