from os import environ

DISCORD_TOKEN = environ["DISCORD_TOKEN"]

PGG_PASSWORD1 = environ["PGG_PASSWORD1"]
PGG_USERNAME1 = environ["PGG_USERNAME1"]
PGG_PASSWORD2 = environ["PGG_PASSWORD2"]
PGG_USERNAME2 = environ["PGG_USERNAME2"]

TAURON_PASSWORD1 = environ["TAURON_PASSWORD1"]
TAURON_USERNAME1 = environ["TAURON_USERNAME1"]
TAURON_PASSWORD2 = environ["TAURON_PASSWORD2"]
TAURON_USERNAME2 = environ["TAURON_USERNAME2"]
TAURON_PASSWORD3 = environ["TAURON_PASSWORD3"]
TAURON_USERNAME3 = environ["TAURON_USERNAME3"]

PESEL1 = environ["PESEL1"]
PESEL2 = environ["PESEL2"]
PESEL3 = environ["PESEL3"]

